apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: applications
    cyclops-ui.com/write-repo: https://github.com/brunokino/cyclops-ui-lab
    cyclops-ui.com/write-revision: main
  creationTimestamp: null
  name: 2nd-app
spec:
  targetNamespace: default
  template:
    path: demo
    repo: https://github.com/cyclops-ui/templates
    sourceType: git
    version: main
  values:
    image: nginx
    name: demo-app
    replicas: 1
    service: true
    version: 1.14.2
status: {}
